source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }
ruby '2.5.1'

gem 'rails', '~> 4.1.5'
gem 'sqlite3'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '~> 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'puma', '~> 3.11'
gem 'turbolinks', '~> 5'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0',     group: :doc

gem 'devise', '~> 3.3.0'


# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.1.0', require: false



group :development do

  gem 'spring'
  
end

